import './loader.css';
import './modal.css';
import './note-preview.css';
import './rich-text-editor.css';
import './tailwind.css';
import 'react-big-calendar/lib/addons/dragAndDrop/styles.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import './calendar.css';
import './scrollbar.css';
