import {
  FaBell,
  FaCalendarAlt,
  FaCheck,
  FaCheckCircle,
  FaCog,
  FaComments,
  FaDownload,
  FaEdit,
  FaHeart,
  FaLinkedin,
  FaLock,
  FaSave,
  FaSearch,
  FaTag,
  FaTrash,
  FaUnlock,
  FaUpload,
  FaUser,
} from 'react-icons/fa';
import { FcGoogle } from 'react-icons/fc';
import { HiOutlineSquaresPlus } from 'react-icons/hi2';
import {
  PiAppleLogoFill,
  PiArrowClockwise,
  PiArrowCounterClockwise,
  PiArrowDown,
  PiArrowLeft,
  PiArrowRight,
  PiArrowUp,
  PiArrowUpRight,
  PiArrowsLeftRight,
  PiBell,
  PiBookOpen,
  PiBookmarkSimple,
  PiBookmarkSimpleFill,
  PiBuildings,
  PiCalendar,
  PiCaretDown,
  PiCaretLeft,
  PiCaretRight,
  PiCaretUpDown,
  PiChartDonut,
  PiChartLine,
  PiClock,
  PiDotsThreeVertical,
  PiEnvelopeSimple,
  PiEye,
  PiEyeSlash,
  PiFingerprint,
  PiGear,
  PiHighlighter,
  PiHouse,
  PiInfo,
  PiListBullets,
  PiListChecks,
  PiListNumbers,
  PiLock,
  PiMagnifyingGlassMinus,
  PiMagnifyingGlassPlus,
  PiMicrophoneFill,
  PiMicrophoneSlashFill,
  PiMinus,
  PiMonitorPlay,
  PiMoon,
  PiNote,
  PiNotePencil,
  PiPaintBrushBroad,
  PiPalette,
  PiPaperPlaneTilt,
  PiPencilSimple,
  PiPhoneFill,
  PiPhoneSlashFill,
  PiPlug,
  PiPlus,
  PiPower,
  PiQuestion,
  PiReadCvLogo,
  PiSealWarning,
  PiShare,
  PiSidebar,
  PiSidebarSimple,
  PiSpeakerSimpleHighFill,
  PiSpeakerSlashFill,
  PiSquaresFour,
  PiSun,
  PiTextAa,
  PiTextAlignCenter,
  PiTextAlignJustify,
  PiTextAlignLeft,
  PiTextAlignRight,
  PiTextB,
  PiTextIndent,
  PiTextItalic,
  PiTextOutdent,
  PiTextStrikethrough,
  PiTextTSlash,
  PiTextUnderline,
  PiTrash,
  PiUser,
  PiUsersThree,
  PiVideoCameraFill,
  PiVideoCameraSlashFill,
  PiWallet,
  PiWarning,
  PiX,
} from 'react-icons/pi';

export const iconMap = {
  // FontAwesome icons
  user: FaUser,
  cog: FaCog,
  search: FaSearch,
  bell: FaBell,
  heart: FaHeart,
  edit: FaEdit,
  trash: FaTrash,
  check: FaCheck,
  times: PiX,
  'arrow-left': PiArrowLeft,
  'arrow-right': PiArrowRight,
  'arrow-up': PiArrowUp,
  'arrow-down': PiArrowDown,
  'arrow-right-up': PiArrowUpRight,
  eye: PiEye,
  'eye-slash': PiEyeSlash,
  lock: FaLock,
  unlock: FaUnlock,
  download: FaDownload,
  upload: FaUpload,
  chat: FaComments,
  send: PiPaperPlaneTilt,
  help: PiQuestion,
  progression: PiChartLine,
  schedule: FaCalendarAlt,
  tag: FaTag,
  save: FaSave,

  // Sidebar icons
  'collapse-sidebar': PiSidebarSimple,
  'expand-sidebar': PiSidebar,
  'open-sidebar': PiSidebar,
  applications: HiOutlineSquaresPlus,
  'caret-down': PiCaretDown,
  'caret-right': PiCaretRight,
  'caret-left': PiCaretLeft,
  cv: PiReadCvLogo,
  notes: PiNote,
  agenda: PiCalendar,
  dashboard: PiSquaresFour,
  simulations: PiMonitorPlay,
  analytics: PiChartDonut,
  'app-notes': PiNotePencil,
  settings: PiGear,
  'help-center': PiQuestion,
  documentation: PiBookOpen,
  power: PiPower,
  billing: PiWallet,
  integrations: PiPlug,
  security: PiFingerprint,
  profile: PiUser,
  'caret-up-down': PiCaretUpDown,
  home: PiHouse,
  login: PiLock,
  register: PiUser,
  about: PiInfo,

  // Organization icons
  organization: PiBuildings,
  members: PiUsersThree,
  invites: PiEnvelopeSimple,
  'view-flip': PiArrowsLeftRight,

  // Global Icons
  plus: PiPlus,
  minus: PiMinus,
  sun: PiSun,
  moon: PiMoon,
  info: PiInfo,
  warning: PiWarning,
  error: PiSealWarning,
  'check-circle': FaCheckCircle,
  'more-vert': PiDotsThreeVertical,

  // Editor icons
  bold: PiTextB,
  italic: PiTextItalic,
  underline: PiTextUnderline,
  strikethrough: PiTextStrikethrough,
  'list-ul': PiListBullets,
  'list-ol': PiListNumbers,
  tasks: PiListChecks,
  'align-left': PiTextAlignLeft,
  'align-center': PiTextAlignCenter,
  'align-right': PiTextAlignRight,
  'align-justify': PiTextAlignJustify,
  indent: PiTextIndent,
  outdent: PiTextOutdent,
  undo: PiArrowCounterClockwise,
  redo: PiArrowClockwise,
  'remove-format': PiTextTSlash,
  'paint-brush': PiPaintBrushBroad,
  'search-plus': PiMagnifyingGlassPlus,
  'search-minus': PiMagnifyingGlassMinus,
  'format-color-text': PiTextAa,
  palette: PiPalette,
  highlighter: PiHighlighter,

  // SimulationArea icons
  speaker: PiSpeakerSimpleHighFill,
  'speaker-off': PiSpeakerSlashFill,
  call: PiPhoneFill,
  'hang-up': PiPhoneSlashFill,
  'mic-on': PiMicrophoneFill,
  'mic-off': PiMicrophoneSlashFill,
  video: PiVideoCameraFill,
  'video-off': PiVideoCameraSlashFill,
  notifications: PiBell,

  // Notes icons
  share: PiShare,
  favorite: PiBookmarkSimple,
  bookmark: PiBookmarkSimple,
  'bookmark-filled': PiBookmarkSimpleFill,
  clock: PiClock,
  delete: PiTrash,
  pencil: PiPencilSimple,

  // Miscellaneous icons
  google: FcGoogle,
  linkedin: FaLinkedin,
  apple: PiAppleLogoFill,
} as const;

export type IconName = keyof typeof iconMap;
