version: "3.9"

services:
  server_cpp:
    build:
      context: ./core/server
      dockerfile: Dockerfile
    container_name: ai_server
    ports:
      - "8088:8088"
    depends_on:
      - behavior_analyzer
      - emotional_analyzer
      - speech_to_text
      - text_to_speech
      - verbal_analyzer

  behavior_analyzer:
    build:
      context: ./microservices/behavior-analyzer
    container_name: behavior_analyzer_services
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5051:5000"

  emotional_analyzer:
    build:
      context: ./microservices/emotional-analyzer
    container_name: emotional_analyzer_services
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5052:5000"

  speech_to_text:
    build:
      context: .
      dockerfile: ./microservices/speech-to-text/Dockerfile
    container_name: speech_to_text_services
    environment:
      - PYTHONUNBUFFERED=1
      - STT_HOST=speech_to_text
      - STT_PORT=8002
      - VOSK_MODEL_PATH=/root/.cache/vosk # model path in cache dir inside container
    ports:
      - "8002:8002"

  text_to_speech:
    build:
      context: .
      dockerfile: ./microservices/text-to-speech/Dockerfile
    container_name: text_to_speech_services
    environment:
      - PYTHONUNBUFFERED=1
      - TTS_HOST=text_to_speech
      - TTS_PORT=8005
    ports:
      - "8005:8005"

  verbal_analyzer:
    build:
      context: ./microservices/verbal-analyzer
    container_name: verbal_analyzer_services
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5055:5000"
