/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrganizationCreatedRouteImport } from './routes/organization-created'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as CvAnalysisRouteImport } from './routes/cv-analysis'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as OrganizationSettingsRouteImport } from './routes/organization/settings'
import { Route as OrganizationMembersRouteImport } from './routes/organization/members'
import { Route as OrganizationInvitesRouteImport } from './routes/organization/invites'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as ApplicationsApplicationIdIndexRouteImport } from './routes/applications/$applicationId/index'
import { Route as ApplicationsApplicationIdSimulationsRouteImport } from './routes/applications/$applicationId/simulations'
import { Route as ApplicationsApplicationIdRoadmapRouteImport } from './routes/applications/$applicationId/roadmap'
import { Route as ApplicationsApplicationIdAnalyticsRouteImport } from './routes/applications/$applicationId/analytics'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreatedRoute = OrganizationCreatedRouteImport.update({
  id: '/organization-created',
  path: '/organization-created',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const CvAnalysisRoute = CvAnalysisRouteImport.update({
  id: '/cv-analysis',
  path: '/cv-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationInvitesRoute = OrganizationInvitesRouteImport.update({
  id: '/organization/invites',
  path: '/organization/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdIndexRoute =
  ApplicationsApplicationIdIndexRouteImport.update({
    id: '/applications/$applicationId/',
    path: '/applications/$applicationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdSimulationsRoute =
  ApplicationsApplicationIdSimulationsRouteImport.update({
    id: '/applications/$applicationId/simulations',
    path: '/applications/$applicationId/simulations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdRoadmapRoute =
  ApplicationsApplicationIdRoadmapRouteImport.update({
    id: '/applications/$applicationId/roadmap',
    path: '/applications/$applicationId/roadmap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdAnalyticsRoute =
  ApplicationsApplicationIdAnalyticsRouteImport.update({
    id: '/applications/$applicationId/analytics',
    path: '/applications/$applicationId/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/ai-chat': typeof AiChatRoute
  '/cv-analysis': typeof CvAnalysisRoute
  '/diary': typeof DiaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization-created': typeof OrganizationCreatedRoute
  '/profile': typeof ProfileRoute
  '/progression': typeof ProgressionRoute
  '/register': typeof RegisterRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulations': typeof SimulationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/organization/invites': typeof OrganizationInvitesRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/applications': typeof ApplicationsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/applications/$applicationId/analytics': typeof ApplicationsApplicationIdAnalyticsRoute
  '/applications/$applicationId/roadmap': typeof ApplicationsApplicationIdRoadmapRoute
  '/applications/$applicationId/simulations': typeof ApplicationsApplicationIdSimulationsRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/ai-chat': typeof AiChatRoute
  '/cv-analysis': typeof CvAnalysisRoute
  '/diary': typeof DiaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization-created': typeof OrganizationCreatedRoute
  '/profile': typeof ProfileRoute
  '/progression': typeof ProgressionRoute
  '/register': typeof RegisterRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulations': typeof SimulationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/organization/invites': typeof OrganizationInvitesRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/applications': typeof ApplicationsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/applications/$applicationId/analytics': typeof ApplicationsApplicationIdAnalyticsRoute
  '/applications/$applicationId/roadmap': typeof ApplicationsApplicationIdRoadmapRoute
  '/applications/$applicationId/simulations': typeof ApplicationsApplicationIdSimulationsRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/ai-chat': typeof AiChatRoute
  '/cv-analysis': typeof CvAnalysisRoute
  '/diary': typeof DiaryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/organization-created': typeof OrganizationCreatedRoute
  '/profile': typeof ProfileRoute
  '/progression': typeof ProgressionRoute
  '/register': typeof RegisterRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulations': typeof SimulationsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/organization/invites': typeof OrganizationInvitesRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/applications/$applicationId/analytics': typeof ApplicationsApplicationIdAnalyticsRoute
  '/applications/$applicationId/roadmap': typeof ApplicationsApplicationIdRoadmapRoute
  '/applications/$applicationId/simulations': typeof ApplicationsApplicationIdSimulationsRoute
  '/applications/$applicationId/': typeof ApplicationsApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agenda'
    | '/ai-chat'
    | '/cv-analysis'
    | '/diary'
    | '/forgot-password'
    | '/login'
    | '/organization-created'
    | '/profile'
    | '/progression'
    | '/register'
    | '/register-organization'
    | '/reset-password'
    | '/simulations'
    | '/verify-email'
    | '/notes/$noteId'
    | '/organization/invites'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
    | '/applications'
    | '/notes'
    | '/organization'
    | '/settings'
    | '/applications/$applicationId/analytics'
    | '/applications/$applicationId/roadmap'
    | '/applications/$applicationId/simulations'
    | '/applications/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agenda'
    | '/ai-chat'
    | '/cv-analysis'
    | '/diary'
    | '/forgot-password'
    | '/login'
    | '/organization-created'
    | '/profile'
    | '/progression'
    | '/register'
    | '/register-organization'
    | '/reset-password'
    | '/simulations'
    | '/verify-email'
    | '/notes/$noteId'
    | '/organization/invites'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
    | '/applications'
    | '/notes'
    | '/organization'
    | '/settings'
    | '/applications/$applicationId/analytics'
    | '/applications/$applicationId/roadmap'
    | '/applications/$applicationId/simulations'
    | '/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agenda'
    | '/ai-chat'
    | '/cv-analysis'
    | '/diary'
    | '/forgot-password'
    | '/login'
    | '/organization-created'
    | '/profile'
    | '/progression'
    | '/register'
    | '/register-organization'
    | '/reset-password'
    | '/simulations'
    | '/verify-email'
    | '/notes/$noteId'
    | '/organization/invites'
    | '/organization/members'
    | '/organization/settings'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/security'
    | '/applications/'
    | '/notes/'
    | '/organization/'
    | '/settings/'
    | '/applications/$applicationId/analytics'
    | '/applications/$applicationId/roadmap'
    | '/applications/$applicationId/simulations'
    | '/applications/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgendaRoute: typeof AgendaRoute
  AiChatRoute: typeof AiChatRoute
  CvAnalysisRoute: typeof CvAnalysisRoute
  DiaryRoute: typeof DiaryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrganizationCreatedRoute: typeof OrganizationCreatedRoute
  ProfileRoute: typeof ProfileRoute
  ProgressionRoute: typeof ProgressionRoute
  RegisterRoute: typeof RegisterRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulationsRoute: typeof SimulationsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  OrganizationInvitesRoute: typeof OrganizationInvitesRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApplicationsApplicationIdAnalyticsRoute: typeof ApplicationsApplicationIdAnalyticsRoute
  ApplicationsApplicationIdRoadmapRoute: typeof ApplicationsApplicationIdRoadmapRoute
  ApplicationsApplicationIdSimulationsRoute: typeof ApplicationsApplicationIdSimulationsRoute
  ApplicationsApplicationIdIndexRoute: typeof ApplicationsApplicationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-created': {
      id: '/organization-created'
      path: '/organization-created'
      fullPath: '/organization-created'
      preLoaderRoute: typeof OrganizationCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-analysis': {
      id: '/cv-analysis'
      path: '/cv-analysis'
      fullPath: '/cv-analysis'
      preLoaderRoute: typeof CvAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/invites': {
      id: '/organization/invites'
      path: '/organization/invites'
      fullPath: '/organization/invites'
      preLoaderRoute: typeof OrganizationInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/': {
      id: '/applications/$applicationId/'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/simulations': {
      id: '/applications/$applicationId/simulations'
      path: '/applications/$applicationId/simulations'
      fullPath: '/applications/$applicationId/simulations'
      preLoaderRoute: typeof ApplicationsApplicationIdSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/roadmap': {
      id: '/applications/$applicationId/roadmap'
      path: '/applications/$applicationId/roadmap'
      fullPath: '/applications/$applicationId/roadmap'
      preLoaderRoute: typeof ApplicationsApplicationIdRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/analytics': {
      id: '/applications/$applicationId/analytics'
      path: '/applications/$applicationId/analytics'
      fullPath: '/applications/$applicationId/analytics'
      preLoaderRoute: typeof ApplicationsApplicationIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgendaRoute: AgendaRoute,
  AiChatRoute: AiChatRoute,
  CvAnalysisRoute: CvAnalysisRoute,
  DiaryRoute: DiaryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrganizationCreatedRoute: OrganizationCreatedRoute,
  ProfileRoute: ProfileRoute,
  ProgressionRoute: ProgressionRoute,
  RegisterRoute: RegisterRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulationsRoute: SimulationsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  OrganizationInvitesRoute: OrganizationInvitesRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApplicationsApplicationIdAnalyticsRoute:
    ApplicationsApplicationIdAnalyticsRoute,
  ApplicationsApplicationIdRoadmapRoute: ApplicationsApplicationIdRoadmapRoute,
  ApplicationsApplicationIdSimulationsRoute:
    ApplicationsApplicationIdSimulationsRoute,
  ApplicationsApplicationIdIndexRoute: ApplicationsApplicationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
